//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MC3_WService
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.comino.com/schema/commontypes")]
    public partial class W2ErrorDetailsStructure
    {

        private string raisedByField;

        private string errorNumberField;

        private string typeField;

        private string logReferenceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string RaisedBy
        {
            get
            {
                return this.raisedByField;
            }
            set
            {
                this.raisedByField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 1)]
        public string ErrorNumber
        {
            get
            {
                return this.errorNumberField;
            }
            set
            {
                this.errorNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string LogReference
        {
            get
            {
                return this.logReferenceField;
            }
            set
            {
                this.logReferenceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.comino.com/schema/securitycommontypes")]
    public partial class SecurityKeyElementStructure
    {

        private string nameField;

        private string idField;

        private SecurityKeyElementStructureFormatType formatTypeField;

        private string lengthField;

        private string additionalTextField;

        private string picklistNameField;

        private string answerField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 1)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public SecurityKeyElementStructureFormatType FormatType
        {
            get
            {
                return this.formatTypeField;
            }
            set
            {
                this.formatTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 3)]
        public string Length
        {
            get
            {
                return this.lengthField;
            }
            set
            {
                this.lengthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string AdditionalText
        {
            get
            {
                return this.additionalTextField;
            }
            set
            {
                this.additionalTextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string PicklistName
        {
            get
            {
                return this.picklistNameField;
            }
            set
            {
                this.picklistNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string Answer
        {
            get
            {
                return this.answerField;
            }
            set
            {
                this.answerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.comino.com/schema/securitycommontypes")]
    public enum SecurityKeyElementStructureFormatType
    {

        /// <remarks/>
        String,

        /// <remarks/>
        Encrypted,

        /// <remarks/>
        Date,

        /// <remarks/>
        Numeric,

        /// <remarks/>
        PickList,

        /// <remarks/>
        Reversible,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.comino.com/schema/securitycommontypes")]
    public partial class SecurityKeyStructure
    {

        private string questionTextField;

        private string statusField;

        private SecurityKeyElementStructure[] securityKeyElementField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string QuestionText
        {
            get
            {
                return this.questionTextField;
            }
            set
            {
                this.questionTextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SecurityKeyElement", Order = 2)]
        public SecurityKeyElementStructure[] SecurityKeyElement
        {
            get
            {
                return this.securityKeyElementField;
            }
            set
            {
                this.securityKeyElementField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.comino.com/schema/securitycommontypes")]
    public partial class SessionSecurityKeyStructure
    {

        private string internetSessionSecurityIDField;

        private SessionSecurityKeyStructureValidated validatedField;

        private SessionSecurityKeyStructureKeyType keyTypeField;

        private string securityGroupField;

        private SecurityKeyStructure securityKeyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 0)]
        public string InternetSessionSecurityID
        {
            get
            {
                return this.internetSessionSecurityIDField;
            }
            set
            {
                this.internetSessionSecurityIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public SessionSecurityKeyStructureValidated Validated
        {
            get
            {
                return this.validatedField;
            }
            set
            {
                this.validatedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public SessionSecurityKeyStructureKeyType KeyType
        {
            get
            {
                return this.keyTypeField;
            }
            set
            {
                this.keyTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string SecurityGroup
        {
            get
            {
                return this.securityGroupField;
            }
            set
            {
                this.securityGroupField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public SecurityKeyStructure SecurityKey
        {
            get
            {
                return this.securityKeyField;
            }
            set
            {
                this.securityKeyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.comino.com/schema/securitycommontypes")]
    public enum SessionSecurityKeyStructureValidated
    {

        /// <remarks/>
        N,

        /// <remarks/>
        Y,

        /// <remarks/>
        U,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.comino.com/schema/securitycommontypes")]
    public enum SessionSecurityKeyStructureKeyType
    {

        /// <remarks/>
        I,

        /// <remarks/>
        S,

        /// <remarks/>
        C,

        /// <remarks/>
        N,

        /// <remarks/>
        P,

        /// <remarks/>
        H,

        /// <remarks/>
        T,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.comino.com/schema/commontypes")]
    public partial class SummaryDetailsStructure
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.comino.com/schema/commontypes")]
    public partial class KeyObjectIndexStructure
    {

        private string keyObjectTypeField;

        private string keyNumberField;

        private string keyTextField;

        private string descriptionField;

        private SummaryDetailsStructure[] summaryDetailsField;

        private string wktSpatialDataField;

        private string displayTitleField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string KeyObjectType
        {
            get
            {
                return this.keyObjectTypeField;
            }
            set
            {
                this.keyObjectTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 1)]
        public string KeyNumber
        {
            get
            {
                return this.keyNumberField;
            }
            set
            {
                this.keyNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string KeyText
        {
            get
            {
                return this.keyTextField;
            }
            set
            {
                this.keyTextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SummaryDetails", Order = 4)]
        public SummaryDetailsStructure[] SummaryDetails
        {
            get
            {
                return this.summaryDetailsField;
            }
            set
            {
                this.summaryDetailsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string WktSpatialData
        {
            get
            {
                return this.wktSpatialDataField;
            }
            set
            {
                this.wktSpatialDataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string DisplayTitle
        {
            get
            {
                return this.displayTitleField;
            }
            set
            {
                this.displayTitleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.comino.com/schema/securitycommontypes")]
    public partial class SessionKOSecurityKeyStructure
    {

        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Key", typeof(KeyObjectIndexStructure), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("SessionSecurityKey", typeof(SessionSecurityKeyStructure), Order = 0)]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.comino.com/schema/commontypes")]
    public partial class SubjectType
    {

        private string securityTokenField;

        private System.DateTime issueInstantField;

        private string sessionIdentifierField;

        private string nonceField;

        private string channelIdentifierField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string SecurityToken
        {
            get
            {
                return this.securityTokenField;
            }
            set
            {
                this.securityTokenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public System.DateTime IssueInstant
        {
            get
            {
                return this.issueInstantField;
            }
            set
            {
                this.issueInstantField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string SessionIdentifier
        {
            get
            {
                return this.sessionIdentifierField;
            }
            set
            {
                this.sessionIdentifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string nonce
        {
            get
            {
                return this.nonceField;
            }
            set
            {
                this.nonceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string ChannelIdentifier
        {
            get
            {
                return this.channelIdentifierField;
            }
            set
            {
                this.channelIdentifierField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.comino.com/wsdl/security/types")]
    public partial class LoginSecurityStructure
    {

        private SubjectType subjectField;

        private CominoLoginSecurityKeys cominoLoginSecurityKeysField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.comino.com/schema/commontypes", Order = 0)]
        public SubjectType Subject
        {
            get
            {
                return this.subjectField;
            }
            set
            {
                this.subjectField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.comino.com/schema", Order = 1)]
        public CominoLoginSecurityKeys CominoLoginSecurityKeys
        {
            get
            {
                return this.cominoLoginSecurityKeysField;
            }
            set
            {
                this.cominoLoginSecurityKeysField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.comino.com/schema")]
    public partial class CominoLoginSecurityKeys
    {

        private string loginNameField;

        private short stagesField;

        private short stageField;

        private SessionKOSecurityKeyStructure[] sessionKOSecurityKeyField;

        private string clientIDField;

        private string internetProfileNameField;

        private string contactNoField;

        private string userIdField;

        private string loginCallTypeField;

        private string callScriptTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string LoginName
        {
            get
            {
                return this.loginNameField;
            }
            set
            {
                this.loginNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public short Stages
        {
            get
            {
                return this.stagesField;
            }
            set
            {
                this.stagesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public short Stage
        {
            get
            {
                return this.stageField;
            }
            set
            {
                this.stageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SessionKOSecurityKey", Order = 3)]
        public SessionKOSecurityKeyStructure[] SessionKOSecurityKey
        {
            get
            {
                return this.sessionKOSecurityKeyField;
            }
            set
            {
                this.sessionKOSecurityKeyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 4)]
        public string ClientID
        {
            get
            {
                return this.clientIDField;
            }
            set
            {
                this.clientIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string InternetProfileName
        {
            get
            {
                return this.internetProfileNameField;
            }
            set
            {
                this.internetProfileNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 6)]
        public string ContactNo
        {
            get
            {
                return this.contactNoField;
            }
            set
            {
                this.contactNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string LoginCallType
        {
            get
            {
                return this.loginCallTypeField;
            }
            set
            {
                this.loginCallTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string CallScriptType
        {
            get
            {
                return this.callScriptTypeField;
            }
            set
            {
                this.callScriptTypeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.comino.com/wsdl/security", ConfigurationName = "MC3_WService.SecurityPortType")]
    public interface SecurityPortType
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.comino.com/wsdl/security/SecurityPortType/dummy", ReplyAction = "http://www.comino.com/wsdl/security/SecurityPortType/getSecurityKeysResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MC3_WService.W2ErrorDetailsStructure), Action = "http://www.w3.org/2005/08/addressing/soap/fault", Name = "W2ErrorDetails", Namespace = "http://www.comino.com/schema/commontypes")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<MC3_WService.getSecurityKeysResponse> getSecurityKeysAsync(MC3_WService.dummy request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.comino.com/wsdl/security/SecurityPortType/dummy", ReplyAction = "http://www.comino.com/wsdl/security/SecurityPortType/loginADAuthenticateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MC3_WService.W2ErrorDetailsStructure), Action = "http://www.w3.org/2005/08/addressing/soap/fault", Name = "W2ErrorDetails", Namespace = "http://www.comino.com/schema/commontypes")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<MC3_WService.loginADAuthenticateResponse> loginADAuthenticateAsync(MC3_WService.dummy request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class dummy
    {

        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http://www.comino.com/schema/commontypes")]
        public string LogRef;

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "dummy", Namespace = "http://www.comino.com/wsdl/security/types", Order = 0)]
        public string dummy1;

        public dummy()
        {
        }

        public dummy(string LogRef, string dummy1)
        {
            this.LogRef = LogRef;
            this.dummy1 = dummy1;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class getSecurityKeysResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.comino.com/wsdl/security/types", Order = 0)]
        public MC3_WService.LoginSecurityStructure LoginSecurity;

        public getSecurityKeysResponse()
        {
        }

        public getSecurityKeysResponse(MC3_WService.LoginSecurityStructure LoginSecurity)
        {
            this.LoginSecurity = LoginSecurity;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.comino.com/wsdl/security/types")]
    public partial class ADAuthenticateStructure
    {

        private SubjectType subjectField;

        private KeyObjectIndexStructure keyObjectIndexField;

        private string userIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.comino.com/schema/commontypes", Order = 0)]
        public SubjectType Subject
        {
            get
            {
                return this.subjectField;
            }
            set
            {
                this.subjectField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.comino.com/schema/commontypes", Order = 1)]
        public KeyObjectIndexStructure KeyObjectIndex
        {
            get
            {
                return this.keyObjectIndexField;
            }
            set
            {
                this.keyObjectIndexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class loginADAuthenticateResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.comino.com/wsdl/security/types", Order = 0)]
        public MC3_WService.ADAuthenticateStructure ADAuthenticateDetails;

        public loginADAuthenticateResponse()
        {
        }

        public loginADAuthenticateResponse(MC3_WService.ADAuthenticateStructure ADAuthenticateDetails)
        {
            this.ADAuthenticateDetails = ADAuthenticateDetails;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface SecurityPortTypeChannel : MC3_WService.SecurityPortType, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class SecurityPortTypeClient : System.ServiceModel.ClientBase<MC3_WService.SecurityPortType>, MC3_WService.SecurityPortType
    {

        public SecurityPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MC3_WService.getSecurityKeysResponse> MC3_WService.SecurityPortType.getSecurityKeysAsync(MC3_WService.dummy request)
        {
            return base.Channel.getSecurityKeysAsync(request);
        }

        public System.Threading.Tasks.Task<MC3_WService.getSecurityKeysResponse> getSecurityKeysAsync(string LogRef, string dummy1)
        {
            MC3_WService.dummy inValue = new MC3_WService.dummy();
            inValue.LogRef = LogRef;
            inValue.dummy1 = dummy1;
            return ((MC3_WService.SecurityPortType)(this)).getSecurityKeysAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MC3_WService.loginADAuthenticateResponse> MC3_WService.SecurityPortType.loginADAuthenticateAsync(MC3_WService.dummy request)
        {
            return base.Channel.loginADAuthenticateAsync(request);
        }

        public System.Threading.Tasks.Task<MC3_WService.loginADAuthenticateResponse> loginADAuthenticateAsync(string LogRef, string dummy1)
        {
            MC3_WService.dummy inValue = new MC3_WService.dummy();
            inValue.LogRef = LogRef;
            inValue.dummy1 = dummy1;
            return ((MC3_WService.SecurityPortType)(this)).loginADAuthenticateAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.comino.com/wsdl/security", ConfigurationName = "MC3_WService.SecuritySubmissionPortType")]
    public interface SecuritySubmissionPortType
    {

        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.comino.com/wsdl/security/SecuritySubmissionPortType/submitSecurityKeys" +
            "Request", ReplyAction = "http://www.comino.com/wsdl/security/SecuritySubmissionPortType/submitSecurityKeys" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(MC3_WService.W2ErrorDetailsStructure), Action = "http://www.w3.org/2005/08/addressing/soap/fault", Name = "W2ErrorDetails", Namespace = "http://www.comino.com/schema/commontypes")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<MC3_WService.submitSecurityKeysResponse> submitSecurityKeysAsync(MC3_WService.submitSecurityKeysRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.comino.com/wsdl/security/SecuritySubmissionPortType/dummy", ReplyAction = "http://www.comino.com/wsdl/security/SecuritySubmissionPortType/logoutResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MC3_WService.W2ErrorDetailsStructure), Action = "http://www.w3.org/2005/08/addressing/soap/fault", Name = "W2ErrorDetails", Namespace = "http://www.comino.com/schema/commontypes")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<MC3_WService.logoutResponse> logoutAsync(MC3_WService.dummy1 request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class submitSecurityKeysRequest
    {

        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http://www.comino.com/schema/commontypes")]
        public MC3_WService.SubjectType Subject;

        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http://www.comino.com/schema/commontypes")]
        public string LogRef;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.comino.com/schema", Order = 0)]
        public MC3_WService.CominoLoginSecurityKeys CominoLoginSecurityKeys;

        public submitSecurityKeysRequest()
        {
        }

        public submitSecurityKeysRequest(MC3_WService.SubjectType Subject, string LogRef, MC3_WService.CominoLoginSecurityKeys CominoLoginSecurityKeys)
        {
            this.Subject = Subject;
            this.LogRef = LogRef;
            this.CominoLoginSecurityKeys = CominoLoginSecurityKeys;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class submitSecurityKeysResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.comino.com/schema", Order = 0)]
        public MC3_WService.CominoLoginSecurityKeys CominoLoginSecurityKeys;

        public submitSecurityKeysResponse()
        {
        }

        public submitSecurityKeysResponse(MC3_WService.CominoLoginSecurityKeys CominoLoginSecurityKeys)
        {
            this.CominoLoginSecurityKeys = CominoLoginSecurityKeys;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.comino.com/schema/commontypes")]
    public partial class GenericServiceResponseStructure
    {

        private KeyObjectIndexStructure keyObjectIndexField;

        private GenericServiceResponseStructureStatus statusField;

        private string infoField;

        private GenericServiceResponseStructureInfoContainsHTML infoContainsHTMLField;

        private bool infoContainsHTMLFieldSpecified;

        private BusinessErrorStructure[] businessErrorsField;

        private string showProcessField;

        private string documentNoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public KeyObjectIndexStructure KeyObjectIndex
        {
            get
            {
                return this.keyObjectIndexField;
            }
            set
            {
                this.keyObjectIndexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public GenericServiceResponseStructureStatus Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string Info
        {
            get
            {
                return this.infoField;
            }
            set
            {
                this.infoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public GenericServiceResponseStructureInfoContainsHTML InfoContainsHTML
        {
            get
            {
                return this.infoContainsHTMLField;
            }
            set
            {
                this.infoContainsHTMLField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InfoContainsHTMLSpecified
        {
            get
            {
                return this.infoContainsHTMLFieldSpecified;
            }
            set
            {
                this.infoContainsHTMLFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("error", IsNullable = false)]
        public BusinessErrorStructure[] BusinessErrors
        {
            get
            {
                return this.businessErrorsField;
            }
            set
            {
                this.businessErrorsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string ShowProcess
        {
            get
            {
                return this.showProcessField;
            }
            set
            {
                this.showProcessField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string DocumentNo
        {
            get
            {
                return this.documentNoField;
            }
            set
            {
                this.documentNoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.comino.com/schema/commontypes")]
    public enum GenericServiceResponseStructureStatus
    {

        /// <remarks/>
        Success,

        /// <remarks/>
        Fail,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.comino.com/schema/commontypes")]
    public enum GenericServiceResponseStructureInfoContainsHTML
    {

        /// <remarks/>
        No,

        /// <remarks/>
        Yes,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.comino.com/schema/commontypes")]
    public partial class BusinessErrorStructure
    {

        private string fieldNameField;

        private string errorTextField;

        private BusinessErrorStructureType typeField;

        private bool typeFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string fieldName
        {
            get
            {
                return this.fieldNameField;
            }
            set
            {
                this.fieldNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string errorText
        {
            get
            {
                return this.errorTextField;
            }
            set
            {
                this.errorTextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public BusinessErrorStructureType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.comino.com/schema/commontypes")]
    public enum BusinessErrorStructureType
    {

        /// <remarks/>
        error,

        /// <remarks/>
        warning,

        /// <remarks/>
        information,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class dummy1
    {

        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http://www.comino.com/schema/commontypes")]
        public MC3_WService.SubjectType Subject;

        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http://www.comino.com/schema/commontypes")]
        public string LogRef;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.comino.com/wsdl/security/types", Order = 0)]
        public string dummy;

        public dummy1()
        {
        }

        public dummy1(MC3_WService.SubjectType Subject, string LogRef, string dummy)
        {
            this.Subject = Subject;
            this.LogRef = LogRef;
            this.dummy = dummy;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class logoutResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.comino.com/schema/commontypes", Order = 0)]
        public MC3_WService.GenericServiceResponseStructure GenericServiceResponse;

        public logoutResponse()
        {
        }

        public logoutResponse(MC3_WService.GenericServiceResponseStructure GenericServiceResponse)
        {
            this.GenericServiceResponse = GenericServiceResponse;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface SecuritySubmissionPortTypeChannel : MC3_WService.SecuritySubmissionPortType, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class SecuritySubmissionPortTypeClient : System.ServiceModel.ClientBase<MC3_WService.SecuritySubmissionPortType>, MC3_WService.SecuritySubmissionPortType
    {

        public SecuritySubmissionPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public System.Threading.Tasks.Task<MC3_WService.submitSecurityKeysResponse> submitSecurityKeysAsync(MC3_WService.submitSecurityKeysRequest request)
        {
            return base.Channel.submitSecurityKeysAsync(request);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MC3_WService.logoutResponse> MC3_WService.SecuritySubmissionPortType.logoutAsync(MC3_WService.dummy1 request)
        {
            return base.Channel.logoutAsync(request);
        }

        public System.Threading.Tasks.Task<MC3_WService.logoutResponse> logoutAsync(MC3_WService.SubjectType Subject, string LogRef, string dummy)
        {
            MC3_WService.dummy1 inValue = new MC3_WService.dummy1();
            inValue.Subject = Subject;
            inValue.LogRef = LogRef;
            inValue.dummy = dummy;
            return ((MC3_WService.SecuritySubmissionPortType)(this)).logoutAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
