//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MC_WService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployerContributionAdvice", Namespace="http://tempuri.org/")]
    public partial class EmployerContributionAdvice : object
    {
        
        private string UserLoginIDField;
        
        private string UserNameField;
        
        private int EmployerIDField;
        
        private string EmployerNameField;
        
        private string ContributionMonthField;
        
        private double MemberContributionField;
        
        private double MemberContribution5050Field;
        
        private double MemberContributionPOESField;
        
        private double MemberContributionARCField;
        
        private double MemberContributionAPCField;
        
        private double EmployerContributionField;
        
        private double EmployerContributionAPCField;
        
        private double EmployeePayMainField;
        
        private double EmployeePay5050Field;
        
        private double DeficitRecField;
        
        private double YearEndBalanceRecField;
        
        private double FundedBenefitsRecField;
        
        private double Miscellaneous_RecField;
        
        private string PaidDirectlyWYPFField;
        
        private System.Nullable<System.DateTime> PaidByChequeDateField;
        
        private string AdditionalInfoField;
        
        private string UploadedFileNameField;
        
        private string PayrollProviderIDField;
        
        private string ClientIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserLoginID
        {
            get
            {
                return this.UserLoginIDField;
            }
            set
            {
                this.UserLoginIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int EmployerID
        {
            get
            {
                return this.EmployerIDField;
            }
            set
            {
                this.EmployerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string EmployerName
        {
            get
            {
                return this.EmployerNameField;
            }
            set
            {
                this.EmployerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ContributionMonth
        {
            get
            {
                return this.ContributionMonthField;
            }
            set
            {
                this.ContributionMonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double MemberContribution
        {
            get
            {
                return this.MemberContributionField;
            }
            set
            {
                this.MemberContributionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double MemberContribution5050
        {
            get
            {
                return this.MemberContribution5050Field;
            }
            set
            {
                this.MemberContribution5050Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public double MemberContributionPOES
        {
            get
            {
                return this.MemberContributionPOESField;
            }
            set
            {
                this.MemberContributionPOESField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public double MemberContributionARC
        {
            get
            {
                return this.MemberContributionARCField;
            }
            set
            {
                this.MemberContributionARCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public double MemberContributionAPC
        {
            get
            {
                return this.MemberContributionAPCField;
            }
            set
            {
                this.MemberContributionAPCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public double EmployerContribution
        {
            get
            {
                return this.EmployerContributionField;
            }
            set
            {
                this.EmployerContributionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public double EmployerContributionAPC
        {
            get
            {
                return this.EmployerContributionAPCField;
            }
            set
            {
                this.EmployerContributionAPCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public double EmployeePayMain
        {
            get
            {
                return this.EmployeePayMainField;
            }
            set
            {
                this.EmployeePayMainField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public double EmployeePay5050
        {
            get
            {
                return this.EmployeePay5050Field;
            }
            set
            {
                this.EmployeePay5050Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public double DeficitRec
        {
            get
            {
                return this.DeficitRecField;
            }
            set
            {
                this.DeficitRecField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public double YearEndBalanceRec
        {
            get
            {
                return this.YearEndBalanceRecField;
            }
            set
            {
                this.YearEndBalanceRecField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public double FundedBenefitsRec
        {
            get
            {
                return this.FundedBenefitsRecField;
            }
            set
            {
                this.FundedBenefitsRecField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public double Miscellaneous_Rec
        {
            get
            {
                return this.Miscellaneous_RecField;
            }
            set
            {
                this.Miscellaneous_RecField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string PaidDirectlyWYPF
        {
            get
            {
                return this.PaidDirectlyWYPFField;
            }
            set
            {
                this.PaidDirectlyWYPFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public System.Nullable<System.DateTime> PaidByChequeDate
        {
            get
            {
                return this.PaidByChequeDateField;
            }
            set
            {
                this.PaidByChequeDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string AdditionalInfo
        {
            get
            {
                return this.AdditionalInfoField;
            }
            set
            {
                this.AdditionalInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string UploadedFileName
        {
            get
            {
                return this.UploadedFileNameField;
            }
            set
            {
                this.UploadedFileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string PayrollProviderID
        {
            get
            {
                return this.PayrollProviderIDField;
            }
            set
            {
                this.PayrollProviderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string ClientID
        {
            get
            {
                return this.ClientIDField;
            }
            set
            {
                this.ClientIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="McCloud", Namespace="http://tempuri.org/")]
    public partial class McCloud : object
    {
        
        private string UserLoginIDField;
        
        private string UserNameField;
        
        private int EmployerIDField;
        
        private string EmployerNameField;
        
        private string UploadedFileNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserLoginID
        {
            get
            {
                return this.UserLoginIDField;
            }
            set
            {
                this.UserLoginIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int EmployerID
        {
            get
            {
                return this.EmployerIDField;
            }
            set
            {
                this.EmployerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string EmployerName
        {
            get
            {
                return this.EmployerNameField;
            }
            set
            {
                this.EmployerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string UploadedFileName
        {
            get
            {
                return this.UploadedFileNameField;
            }
            set
            {
                this.UploadedFileNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployerProcessAllocate", Namespace="http://tempuri.org/")]
    public partial class EmployerProcessAllocate : object
    {
        
        private string ToAllocateUserIDField;
        
        private string ProcessAssignToTypeField;
        
        private int ProcessNoField;
        
        private string UserWhoAllocateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ToAllocateUserID
        {
            get
            {
                return this.ToAllocateUserIDField;
            }
            set
            {
                this.ToAllocateUserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ProcessAssignToType
        {
            get
            {
                return this.ProcessAssignToTypeField;
            }
            set
            {
                this.ProcessAssignToTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int ProcessNo
        {
            get
            {
                return this.ProcessNoField;
            }
            set
            {
                this.ProcessNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UserWhoAllocate
        {
            get
            {
                return this.UserWhoAllocateField;
            }
            set
            {
                this.UserWhoAllocateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employer", Namespace="http://tempuri.org/")]
    public partial class Employer : object
    {
        
        private string EmployerNameField;
        
        private string TypeOfBodyField;
        
        private string EmployerRefField;
        
        private string PFRField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EmployerName
        {
            get
            {
                return this.EmployerNameField;
            }
            set
            {
                this.EmployerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TypeOfBody
        {
            get
            {
                return this.TypeOfBodyField;
            }
            set
            {
                this.TypeOfBodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EmployerRef
        {
            get
            {
                return this.EmployerRefField;
            }
            set
            {
                this.EmployerRefField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PFR
        {
            get
            {
                return this.PFRField;
            }
            set
            {
                this.PFRField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginDetails", Namespace="http://tempuri.org/")]
    public partial class LoginDetails : object
    {
        
        private string LoginIDField;
        
        private string PaylocationIDField;
        
        private string PaylocationNameField;
        
        private string ContactNameField;
        
        private string PaylocationRefField;
        
        private string FinanceBusinessPartnerField;
        
        private string ClientIDField;
        
        private string Login_EmailField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LoginID
        {
            get
            {
                return this.LoginIDField;
            }
            set
            {
                this.LoginIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PaylocationID
        {
            get
            {
                return this.PaylocationIDField;
            }
            set
            {
                this.PaylocationIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PaylocationName
        {
            get
            {
                return this.PaylocationNameField;
            }
            set
            {
                this.PaylocationNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ContactName
        {
            get
            {
                return this.ContactNameField;
            }
            set
            {
                this.ContactNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PaylocationRef
        {
            get
            {
                return this.PaylocationRefField;
            }
            set
            {
                this.PaylocationRefField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string FinanceBusinessPartner
        {
            get
            {
                return this.FinanceBusinessPartnerField;
            }
            set
            {
                this.FinanceBusinessPartnerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ClientID
        {
            get
            {
                return this.ClientIDField;
            }
            set
            {
                this.ClientIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Login_Email
        {
            get
            {
                return this.Login_EmailField;
            }
            set
            {
                this.Login_EmailField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployerGroupWorkTrays", Namespace="http://tempuri.org/")]
    public partial class EmployerGroupWorkTrays : object
    {
        
        private string ProcessNameField;
        
        private string PaylocationNameField;
        
        private string TrayField;
        
        private double HowManyField;
        
        private string ProcessTypeIDField;
        
        private double PaylocationIDField;
        
        private string TrayIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProcessName
        {
            get
            {
                return this.ProcessNameField;
            }
            set
            {
                this.ProcessNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PaylocationName
        {
            get
            {
                return this.PaylocationNameField;
            }
            set
            {
                this.PaylocationNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Tray
        {
            get
            {
                return this.TrayField;
            }
            set
            {
                this.TrayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double HowMany
        {
            get
            {
                return this.HowManyField;
            }
            set
            {
                this.HowManyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ProcessTypeID
        {
            get
            {
                return this.ProcessTypeIDField;
            }
            set
            {
                this.ProcessTypeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double PaylocationID
        {
            get
            {
                return this.PaylocationIDField;
            }
            set
            {
                this.PaylocationIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TrayID
        {
            get
            {
                return this.TrayIDField;
            }
            set
            {
                this.TrayIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployerGroupWorkTrayDetails", Namespace="http://tempuri.org/")]
    public partial class EmployerGroupWorkTrayDetails : object
    {
        
        private string ProcessNoField;
        
        private string SurNameField;
        
        private string ForeNamesField;
        
        private string FolderRefField;
        
        private string PayRefField;
        
        private int MissingField;
        
        private double PayJumpField;
        
        private double PayFallField;
        
        private double SuspectLeaverField;
        
        private double NoMonthly4Field;
        
        private double NoMonthly5Field;
        
        private double FinalPayMultiField;
        
        private double FinalPayMissingField;
        
        private double FinalPayLowField;
        
        private double FinalPayUpField;
        
        private double FinalPayDownField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProcessNo
        {
            get
            {
                return this.ProcessNoField;
            }
            set
            {
                this.ProcessNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SurName
        {
            get
            {
                return this.SurNameField;
            }
            set
            {
                this.SurNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ForeNames
        {
            get
            {
                return this.ForeNamesField;
            }
            set
            {
                this.ForeNamesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FolderRef
        {
            get
            {
                return this.FolderRefField;
            }
            set
            {
                this.FolderRefField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PayRef
        {
            get
            {
                return this.PayRefField;
            }
            set
            {
                this.PayRefField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Missing
        {
            get
            {
                return this.MissingField;
            }
            set
            {
                this.MissingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double PayJump
        {
            get
            {
                return this.PayJumpField;
            }
            set
            {
                this.PayJumpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public double PayFall
        {
            get
            {
                return this.PayFallField;
            }
            set
            {
                this.PayFallField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public double SuspectLeaver
        {
            get
            {
                return this.SuspectLeaverField;
            }
            set
            {
                this.SuspectLeaverField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public double NoMonthly4
        {
            get
            {
                return this.NoMonthly4Field;
            }
            set
            {
                this.NoMonthly4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public double NoMonthly5
        {
            get
            {
                return this.NoMonthly5Field;
            }
            set
            {
                this.NoMonthly5Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public double FinalPayMulti
        {
            get
            {
                return this.FinalPayMultiField;
            }
            set
            {
                this.FinalPayMultiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public double FinalPayMissing
        {
            get
            {
                return this.FinalPayMissingField;
            }
            set
            {
                this.FinalPayMissingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public double FinalPayLow
        {
            get
            {
                return this.FinalPayLowField;
            }
            set
            {
                this.FinalPayLowField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public double FinalPayUp
        {
            get
            {
                return this.FinalPayUpField;
            }
            set
            {
                this.FinalPayUpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public double FinalPayDown
        {
            get
            {
                return this.FinalPayDownField;
            }
            set
            {
                this.FinalPayDownField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployerGroupWorkTrayUser", Namespace="http://tempuri.org/")]
    public partial class EmployerGroupWorkTrayUser : object
    {
        
        private string UserIDField;
        
        private string UserNameField;
        
        private string UserTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserType
        {
            get
            {
                return this.UserTypeField;
            }
            set
            {
                this.UserTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MC_WService.EmployerWSSoap")]
    public interface EmployerWSSoap
    {
        
        // CODEGEN: Generating message contract since element name employerContributionAdvice from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_EmployerContributionAdvice", ReplyAction="*")]
        MC_WService.Add_EmployerContributionAdviceResponse Add_EmployerContributionAdvice(MC_WService.Add_EmployerContributionAdviceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_EmployerContributionAdvice", ReplyAction="*")]
        System.Threading.Tasks.Task<MC_WService.Add_EmployerContributionAdviceResponse> Add_EmployerContributionAdviceAsync(MC_WService.Add_EmployerContributionAdviceRequest request);
        
        // CODEGEN: Generating message contract since element name mcCloud from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_McCloudFile", ReplyAction="*")]
        MC_WService.Add_McCloudFileResponse Add_McCloudFile(MC_WService.Add_McCloudFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_McCloudFile", ReplyAction="*")]
        System.Threading.Tasks.Task<MC_WService.Add_McCloudFileResponse> Add_McCloudFileAsync(MC_WService.Add_McCloudFileRequest request);
        
        // CODEGEN: Generating message contract since element name employerProcessAllocate from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Allocate_ProcessToUser", ReplyAction="*")]
        MC_WService.Allocate_ProcessToUserResponse Allocate_ProcessToUser(MC_WService.Allocate_ProcessToUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Allocate_ProcessToUser", ReplyAction="*")]
        System.Threading.Tasks.Task<MC_WService.Allocate_ProcessToUserResponse> Allocate_ProcessToUserAsync(MC_WService.Allocate_ProcessToUserRequest request);
        
        // CODEGEN: Generating message contract since element name paylocationID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_MonthlyContribProcessLaunchInfo", ReplyAction="*")]
        MC_WService.Add_MonthlyContribProcessLaunchInfoResponse Add_MonthlyContribProcessLaunchInfo(MC_WService.Add_MonthlyContribProcessLaunchInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_MonthlyContribProcessLaunchInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<MC_WService.Add_MonthlyContribProcessLaunchInfoResponse> Add_MonthlyContribProcessLaunchInfoAsync(MC_WService.Add_MonthlyContribProcessLaunchInfoRequest request);
        
        // CODEGEN: Generating message contract since element name Get_EmployerListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_EmployerList", ReplyAction="*")]
        MC_WService.Get_EmployerListResponse Get_EmployerList(MC_WService.Get_EmployerListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_EmployerList", ReplyAction="*")]
        System.Threading.Tasks.Task<MC_WService.Get_EmployerListResponse> Get_EmployerListAsync(MC_WService.Get_EmployerListRequest request);
        
        // CODEGEN: Generating message contract since element name loginID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLoginDetails", ReplyAction="*")]
        MC_WService.GetLoginDetailsResponse GetLoginDetails(MC_WService.GetLoginDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLoginDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<MC_WService.GetLoginDetailsResponse> GetLoginDetailsAsync(MC_WService.GetLoginDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name loginID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPayrollproviders", ReplyAction="*")]
        MC_WService.GetPayrollprovidersResponse GetPayrollproviders(MC_WService.GetPayrollprovidersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPayrollproviders", ReplyAction="*")]
        System.Threading.Tasks.Task<MC_WService.GetPayrollprovidersResponse> GetPayrollprovidersAsync(MC_WService.GetPayrollprovidersRequest request);
        
        // CODEGEN: Generating message contract since element name loginID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_EmployerGroupWorkTrays", ReplyAction="*")]
        MC_WService.Get_EmployerGroupWorkTraysResponse Get_EmployerGroupWorkTrays(MC_WService.Get_EmployerGroupWorkTraysRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_EmployerGroupWorkTrays", ReplyAction="*")]
        System.Threading.Tasks.Task<MC_WService.Get_EmployerGroupWorkTraysResponse> Get_EmployerGroupWorkTraysAsync(MC_WService.Get_EmployerGroupWorkTraysRequest request);
        
        // CODEGEN: Generating message contract since element name processTypdID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployerProcessGroupTrayDetails", ReplyAction="*")]
        MC_WService.GetEmployerProcessGroupTrayDetailsResponse GetEmployerProcessGroupTrayDetails(MC_WService.GetEmployerProcessGroupTrayDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployerProcessGroupTrayDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<MC_WService.GetEmployerProcessGroupTrayDetailsResponse> GetEmployerProcessGroupTrayDetailsAsync(MC_WService.GetEmployerProcessGroupTrayDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name loginID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_EmployerGroupWorkTrayUsers", ReplyAction="*")]
        MC_WService.Get_EmployerGroupWorkTrayUsersResponse Get_EmployerGroupWorkTrayUsers(MC_WService.Get_EmployerGroupWorkTrayUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_EmployerGroupWorkTrayUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<MC_WService.Get_EmployerGroupWorkTrayUsersResponse> Get_EmployerGroupWorkTrayUsersAsync(MC_WService.Get_EmployerGroupWorkTrayUsersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add_EmployerContributionAdviceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add_EmployerContributionAdvice", Namespace="http://tempuri.org/", Order=0)]
        public MC_WService.Add_EmployerContributionAdviceRequestBody Body;
        
        public Add_EmployerContributionAdviceRequest()
        {
        }
        
        public Add_EmployerContributionAdviceRequest(MC_WService.Add_EmployerContributionAdviceRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Add_EmployerContributionAdviceRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MC_WService.EmployerContributionAdvice employerContributionAdvice;
        
        public Add_EmployerContributionAdviceRequestBody()
        {
        }
        
        public Add_EmployerContributionAdviceRequestBody(MC_WService.EmployerContributionAdvice employerContributionAdvice)
        {
            this.employerContributionAdvice = employerContributionAdvice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add_EmployerContributionAdviceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add_EmployerContributionAdviceResponse", Namespace="http://tempuri.org/", Order=0)]
        public MC_WService.Add_EmployerContributionAdviceResponseBody Body;
        
        public Add_EmployerContributionAdviceResponse()
        {
        }
        
        public Add_EmployerContributionAdviceResponse(MC_WService.Add_EmployerContributionAdviceResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Add_EmployerContributionAdviceResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Add_EmployerContributionAdviceResult;
        
        public Add_EmployerContributionAdviceResponseBody()
        {
        }
        
        public Add_EmployerContributionAdviceResponseBody(string Add_EmployerContributionAdviceResult)
        {
            this.Add_EmployerContributionAdviceResult = Add_EmployerContributionAdviceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add_McCloudFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add_McCloudFile", Namespace="http://tempuri.org/", Order=0)]
        public MC_WService.Add_McCloudFileRequestBody Body;
        
        public Add_McCloudFileRequest()
        {
        }
        
        public Add_McCloudFileRequest(MC_WService.Add_McCloudFileRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Add_McCloudFileRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MC_WService.McCloud mcCloud;
        
        public Add_McCloudFileRequestBody()
        {
        }
        
        public Add_McCloudFileRequestBody(MC_WService.McCloud mcCloud)
        {
            this.mcCloud = mcCloud;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add_McCloudFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add_McCloudFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public MC_WService.Add_McCloudFileResponseBody Body;
        
        public Add_McCloudFileResponse()
        {
        }
        
        public Add_McCloudFileResponse(MC_WService.Add_McCloudFileResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Add_McCloudFileResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Add_McCloudFileResult;
        
        public Add_McCloudFileResponseBody()
        {
        }
        
        public Add_McCloudFileResponseBody(string Add_McCloudFileResult)
        {
            this.Add_McCloudFileResult = Add_McCloudFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Allocate_ProcessToUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Allocate_ProcessToUser", Namespace="http://tempuri.org/", Order=0)]
        public MC_WService.Allocate_ProcessToUserRequestBody Body;
        
        public Allocate_ProcessToUserRequest()
        {
        }
        
        public Allocate_ProcessToUserRequest(MC_WService.Allocate_ProcessToUserRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Allocate_ProcessToUserRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MC_WService.EmployerProcessAllocate employerProcessAllocate;
        
        public Allocate_ProcessToUserRequestBody()
        {
        }
        
        public Allocate_ProcessToUserRequestBody(MC_WService.EmployerProcessAllocate employerProcessAllocate)
        {
            this.employerProcessAllocate = employerProcessAllocate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Allocate_ProcessToUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Allocate_ProcessToUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public MC_WService.Allocate_ProcessToUserResponseBody Body;
        
        public Allocate_ProcessToUserResponse()
        {
        }
        
        public Allocate_ProcessToUserResponse(MC_WService.Allocate_ProcessToUserResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Allocate_ProcessToUserResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Allocate_ProcessToUserResult;
        
        public Allocate_ProcessToUserResponseBody()
        {
        }
        
        public Allocate_ProcessToUserResponseBody(string Allocate_ProcessToUserResult)
        {
            this.Allocate_ProcessToUserResult = Allocate_ProcessToUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add_MonthlyContribProcessLaunchInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add_MonthlyContribProcessLaunchInfo", Namespace="http://tempuri.org/", Order=0)]
        public MC_WService.Add_MonthlyContribProcessLaunchInfoRequestBody Body;
        
        public Add_MonthlyContribProcessLaunchInfoRequest()
        {
        }
        
        public Add_MonthlyContribProcessLaunchInfoRequest(MC_WService.Add_MonthlyContribProcessLaunchInfoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Add_MonthlyContribProcessLaunchInfoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string paylocationID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fileName;
        
        public Add_MonthlyContribProcessLaunchInfoRequestBody()
        {
        }
        
        public Add_MonthlyContribProcessLaunchInfoRequestBody(string paylocationID, string fileName)
        {
            this.paylocationID = paylocationID;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add_MonthlyContribProcessLaunchInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add_MonthlyContribProcessLaunchInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public MC_WService.Add_MonthlyContribProcessLaunchInfoResponseBody Body;
        
        public Add_MonthlyContribProcessLaunchInfoResponse()
        {
        }
        
        public Add_MonthlyContribProcessLaunchInfoResponse(MC_WService.Add_MonthlyContribProcessLaunchInfoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Add_MonthlyContribProcessLaunchInfoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Add_MonthlyContribProcessLaunchInfoResult;
        
        public Add_MonthlyContribProcessLaunchInfoResponseBody()
        {
        }
        
        public Add_MonthlyContribProcessLaunchInfoResponseBody(string Add_MonthlyContribProcessLaunchInfoResult)
        {
            this.Add_MonthlyContribProcessLaunchInfoResult = Add_MonthlyContribProcessLaunchInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_EmployerListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_EmployerList", Namespace="http://tempuri.org/", Order=0)]
        public MC_WService.Get_EmployerListRequestBody Body;
        
        public Get_EmployerListRequest()
        {
        }
        
        public Get_EmployerListRequest(MC_WService.Get_EmployerListRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Get_EmployerListRequestBody
    {
        
        public Get_EmployerListRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_EmployerListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_EmployerListResponse", Namespace="http://tempuri.org/", Order=0)]
        public MC_WService.Get_EmployerListResponseBody Body;
        
        public Get_EmployerListResponse()
        {
        }
        
        public Get_EmployerListResponse(MC_WService.Get_EmployerListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_EmployerListResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MC_WService.Employer[] Get_EmployerListResult;
        
        public Get_EmployerListResponseBody()
        {
        }
        
        public Get_EmployerListResponseBody(MC_WService.Employer[] Get_EmployerListResult)
        {
            this.Get_EmployerListResult = Get_EmployerListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLoginDetailsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLoginDetails", Namespace="http://tempuri.org/", Order=0)]
        public MC_WService.GetLoginDetailsRequestBody Body;
        
        public GetLoginDetailsRequest()
        {
        }
        
        public GetLoginDetailsRequest(MC_WService.GetLoginDetailsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLoginDetailsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginID;
        
        public GetLoginDetailsRequestBody()
        {
        }
        
        public GetLoginDetailsRequestBody(string loginID)
        {
            this.loginID = loginID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLoginDetailsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLoginDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public MC_WService.GetLoginDetailsResponseBody Body;
        
        public GetLoginDetailsResponse()
        {
        }
        
        public GetLoginDetailsResponse(MC_WService.GetLoginDetailsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLoginDetailsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MC_WService.LoginDetails GetLoginDetailsResult;
        
        public GetLoginDetailsResponseBody()
        {
        }
        
        public GetLoginDetailsResponseBody(MC_WService.LoginDetails GetLoginDetailsResult)
        {
            this.GetLoginDetailsResult = GetLoginDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPayrollprovidersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPayrollproviders", Namespace="http://tempuri.org/", Order=0)]
        public MC_WService.GetPayrollprovidersRequestBody Body;
        
        public GetPayrollprovidersRequest()
        {
        }
        
        public GetPayrollprovidersRequest(MC_WService.GetPayrollprovidersRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPayrollprovidersRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginID;
        
        public GetPayrollprovidersRequestBody()
        {
        }
        
        public GetPayrollprovidersRequestBody(string loginID)
        {
            this.loginID = loginID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPayrollprovidersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPayrollprovidersResponse", Namespace="http://tempuri.org/", Order=0)]
        public MC_WService.GetPayrollprovidersResponseBody Body;
        
        public GetPayrollprovidersResponse()
        {
        }
        
        public GetPayrollprovidersResponse(MC_WService.GetPayrollprovidersResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPayrollprovidersResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MC_WService.LoginDetails[] GetPayrollprovidersResult;
        
        public GetPayrollprovidersResponseBody()
        {
        }
        
        public GetPayrollprovidersResponseBody(MC_WService.LoginDetails[] GetPayrollprovidersResult)
        {
            this.GetPayrollprovidersResult = GetPayrollprovidersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_EmployerGroupWorkTraysRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_EmployerGroupWorkTrays", Namespace="http://tempuri.org/", Order=0)]
        public MC_WService.Get_EmployerGroupWorkTraysRequestBody Body;
        
        public Get_EmployerGroupWorkTraysRequest()
        {
        }
        
        public Get_EmployerGroupWorkTraysRequest(MC_WService.Get_EmployerGroupWorkTraysRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_EmployerGroupWorkTraysRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginID;
        
        public Get_EmployerGroupWorkTraysRequestBody()
        {
        }
        
        public Get_EmployerGroupWorkTraysRequestBody(string loginID)
        {
            this.loginID = loginID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_EmployerGroupWorkTraysResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_EmployerGroupWorkTraysResponse", Namespace="http://tempuri.org/", Order=0)]
        public MC_WService.Get_EmployerGroupWorkTraysResponseBody Body;
        
        public Get_EmployerGroupWorkTraysResponse()
        {
        }
        
        public Get_EmployerGroupWorkTraysResponse(MC_WService.Get_EmployerGroupWorkTraysResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_EmployerGroupWorkTraysResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MC_WService.EmployerGroupWorkTrays[] Get_EmployerGroupWorkTraysResult;
        
        public Get_EmployerGroupWorkTraysResponseBody()
        {
        }
        
        public Get_EmployerGroupWorkTraysResponseBody(MC_WService.EmployerGroupWorkTrays[] Get_EmployerGroupWorkTraysResult)
        {
            this.Get_EmployerGroupWorkTraysResult = Get_EmployerGroupWorkTraysResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployerProcessGroupTrayDetailsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployerProcessGroupTrayDetails", Namespace="http://tempuri.org/", Order=0)]
        public MC_WService.GetEmployerProcessGroupTrayDetailsRequestBody Body;
        
        public GetEmployerProcessGroupTrayDetailsRequest()
        {
        }
        
        public GetEmployerProcessGroupTrayDetailsRequest(MC_WService.GetEmployerProcessGroupTrayDetailsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployerProcessGroupTrayDetailsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string processTypdID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int paylocationID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string trayID;
        
        public GetEmployerProcessGroupTrayDetailsRequestBody()
        {
        }
        
        public GetEmployerProcessGroupTrayDetailsRequestBody(string processTypdID, int paylocationID, string trayID)
        {
            this.processTypdID = processTypdID;
            this.paylocationID = paylocationID;
            this.trayID = trayID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployerProcessGroupTrayDetailsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployerProcessGroupTrayDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public MC_WService.GetEmployerProcessGroupTrayDetailsResponseBody Body;
        
        public GetEmployerProcessGroupTrayDetailsResponse()
        {
        }
        
        public GetEmployerProcessGroupTrayDetailsResponse(MC_WService.GetEmployerProcessGroupTrayDetailsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployerProcessGroupTrayDetailsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MC_WService.EmployerGroupWorkTrayDetails[] GetEmployerProcessGroupTrayDetailsResult;
        
        public GetEmployerProcessGroupTrayDetailsResponseBody()
        {
        }
        
        public GetEmployerProcessGroupTrayDetailsResponseBody(MC_WService.EmployerGroupWorkTrayDetails[] GetEmployerProcessGroupTrayDetailsResult)
        {
            this.GetEmployerProcessGroupTrayDetailsResult = GetEmployerProcessGroupTrayDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_EmployerGroupWorkTrayUsersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_EmployerGroupWorkTrayUsers", Namespace="http://tempuri.org/", Order=0)]
        public MC_WService.Get_EmployerGroupWorkTrayUsersRequestBody Body;
        
        public Get_EmployerGroupWorkTrayUsersRequest()
        {
        }
        
        public Get_EmployerGroupWorkTrayUsersRequest(MC_WService.Get_EmployerGroupWorkTrayUsersRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_EmployerGroupWorkTrayUsersRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginID;
        
        public Get_EmployerGroupWorkTrayUsersRequestBody()
        {
        }
        
        public Get_EmployerGroupWorkTrayUsersRequestBody(string loginID)
        {
            this.loginID = loginID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_EmployerGroupWorkTrayUsersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_EmployerGroupWorkTrayUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public MC_WService.Get_EmployerGroupWorkTrayUsersResponseBody Body;
        
        public Get_EmployerGroupWorkTrayUsersResponse()
        {
        }
        
        public Get_EmployerGroupWorkTrayUsersResponse(MC_WService.Get_EmployerGroupWorkTrayUsersResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_EmployerGroupWorkTrayUsersResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MC_WService.EmployerGroupWorkTrayUser[] Get_EmployerGroupWorkTrayUsersResult;
        
        public Get_EmployerGroupWorkTrayUsersResponseBody()
        {
        }
        
        public Get_EmployerGroupWorkTrayUsersResponseBody(MC_WService.EmployerGroupWorkTrayUser[] Get_EmployerGroupWorkTrayUsersResult)
        {
            this.Get_EmployerGroupWorkTrayUsersResult = Get_EmployerGroupWorkTrayUsersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface EmployerWSSoapChannel : MC_WService.EmployerWSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class EmployerWSSoapClient : System.ServiceModel.ClientBase<MC_WService.EmployerWSSoap>, MC_WService.EmployerWSSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EmployerWSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(EmployerWSSoapClient.GetBindingForEndpoint(endpointConfiguration), EmployerWSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmployerWSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EmployerWSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmployerWSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EmployerWSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmployerWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MC_WService.Add_EmployerContributionAdviceResponse MC_WService.EmployerWSSoap.Add_EmployerContributionAdvice(MC_WService.Add_EmployerContributionAdviceRequest request)
        {
            return base.Channel.Add_EmployerContributionAdvice(request);
        }
        
        public string Add_EmployerContributionAdvice(MC_WService.EmployerContributionAdvice employerContributionAdvice)
        {
            MC_WService.Add_EmployerContributionAdviceRequest inValue = new MC_WService.Add_EmployerContributionAdviceRequest();
            inValue.Body = new MC_WService.Add_EmployerContributionAdviceRequestBody();
            inValue.Body.employerContributionAdvice = employerContributionAdvice;
            MC_WService.Add_EmployerContributionAdviceResponse retVal = ((MC_WService.EmployerWSSoap)(this)).Add_EmployerContributionAdvice(inValue);
            return retVal.Body.Add_EmployerContributionAdviceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MC_WService.Add_EmployerContributionAdviceResponse> MC_WService.EmployerWSSoap.Add_EmployerContributionAdviceAsync(MC_WService.Add_EmployerContributionAdviceRequest request)
        {
            return base.Channel.Add_EmployerContributionAdviceAsync(request);
        }
        
        public System.Threading.Tasks.Task<MC_WService.Add_EmployerContributionAdviceResponse> Add_EmployerContributionAdviceAsync(MC_WService.EmployerContributionAdvice employerContributionAdvice)
        {
            MC_WService.Add_EmployerContributionAdviceRequest inValue = new MC_WService.Add_EmployerContributionAdviceRequest();
            inValue.Body = new MC_WService.Add_EmployerContributionAdviceRequestBody();
            inValue.Body.employerContributionAdvice = employerContributionAdvice;
            return ((MC_WService.EmployerWSSoap)(this)).Add_EmployerContributionAdviceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MC_WService.Add_McCloudFileResponse MC_WService.EmployerWSSoap.Add_McCloudFile(MC_WService.Add_McCloudFileRequest request)
        {
            return base.Channel.Add_McCloudFile(request);
        }
        
        public string Add_McCloudFile(MC_WService.McCloud mcCloud)
        {
            MC_WService.Add_McCloudFileRequest inValue = new MC_WService.Add_McCloudFileRequest();
            inValue.Body = new MC_WService.Add_McCloudFileRequestBody();
            inValue.Body.mcCloud = mcCloud;
            MC_WService.Add_McCloudFileResponse retVal = ((MC_WService.EmployerWSSoap)(this)).Add_McCloudFile(inValue);
            return retVal.Body.Add_McCloudFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MC_WService.Add_McCloudFileResponse> MC_WService.EmployerWSSoap.Add_McCloudFileAsync(MC_WService.Add_McCloudFileRequest request)
        {
            return base.Channel.Add_McCloudFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<MC_WService.Add_McCloudFileResponse> Add_McCloudFileAsync(MC_WService.McCloud mcCloud)
        {
            MC_WService.Add_McCloudFileRequest inValue = new MC_WService.Add_McCloudFileRequest();
            inValue.Body = new MC_WService.Add_McCloudFileRequestBody();
            inValue.Body.mcCloud = mcCloud;
            return ((MC_WService.EmployerWSSoap)(this)).Add_McCloudFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MC_WService.Allocate_ProcessToUserResponse MC_WService.EmployerWSSoap.Allocate_ProcessToUser(MC_WService.Allocate_ProcessToUserRequest request)
        {
            return base.Channel.Allocate_ProcessToUser(request);
        }
        
        public string Allocate_ProcessToUser(MC_WService.EmployerProcessAllocate employerProcessAllocate)
        {
            MC_WService.Allocate_ProcessToUserRequest inValue = new MC_WService.Allocate_ProcessToUserRequest();
            inValue.Body = new MC_WService.Allocate_ProcessToUserRequestBody();
            inValue.Body.employerProcessAllocate = employerProcessAllocate;
            MC_WService.Allocate_ProcessToUserResponse retVal = ((MC_WService.EmployerWSSoap)(this)).Allocate_ProcessToUser(inValue);
            return retVal.Body.Allocate_ProcessToUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MC_WService.Allocate_ProcessToUserResponse> MC_WService.EmployerWSSoap.Allocate_ProcessToUserAsync(MC_WService.Allocate_ProcessToUserRequest request)
        {
            return base.Channel.Allocate_ProcessToUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<MC_WService.Allocate_ProcessToUserResponse> Allocate_ProcessToUserAsync(MC_WService.EmployerProcessAllocate employerProcessAllocate)
        {
            MC_WService.Allocate_ProcessToUserRequest inValue = new MC_WService.Allocate_ProcessToUserRequest();
            inValue.Body = new MC_WService.Allocate_ProcessToUserRequestBody();
            inValue.Body.employerProcessAllocate = employerProcessAllocate;
            return ((MC_WService.EmployerWSSoap)(this)).Allocate_ProcessToUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MC_WService.Add_MonthlyContribProcessLaunchInfoResponse MC_WService.EmployerWSSoap.Add_MonthlyContribProcessLaunchInfo(MC_WService.Add_MonthlyContribProcessLaunchInfoRequest request)
        {
            return base.Channel.Add_MonthlyContribProcessLaunchInfo(request);
        }
        
        public string Add_MonthlyContribProcessLaunchInfo(string paylocationID, string fileName)
        {
            MC_WService.Add_MonthlyContribProcessLaunchInfoRequest inValue = new MC_WService.Add_MonthlyContribProcessLaunchInfoRequest();
            inValue.Body = new MC_WService.Add_MonthlyContribProcessLaunchInfoRequestBody();
            inValue.Body.paylocationID = paylocationID;
            inValue.Body.fileName = fileName;
            MC_WService.Add_MonthlyContribProcessLaunchInfoResponse retVal = ((MC_WService.EmployerWSSoap)(this)).Add_MonthlyContribProcessLaunchInfo(inValue);
            return retVal.Body.Add_MonthlyContribProcessLaunchInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MC_WService.Add_MonthlyContribProcessLaunchInfoResponse> MC_WService.EmployerWSSoap.Add_MonthlyContribProcessLaunchInfoAsync(MC_WService.Add_MonthlyContribProcessLaunchInfoRequest request)
        {
            return base.Channel.Add_MonthlyContribProcessLaunchInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<MC_WService.Add_MonthlyContribProcessLaunchInfoResponse> Add_MonthlyContribProcessLaunchInfoAsync(string paylocationID, string fileName)
        {
            MC_WService.Add_MonthlyContribProcessLaunchInfoRequest inValue = new MC_WService.Add_MonthlyContribProcessLaunchInfoRequest();
            inValue.Body = new MC_WService.Add_MonthlyContribProcessLaunchInfoRequestBody();
            inValue.Body.paylocationID = paylocationID;
            inValue.Body.fileName = fileName;
            return ((MC_WService.EmployerWSSoap)(this)).Add_MonthlyContribProcessLaunchInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MC_WService.Get_EmployerListResponse MC_WService.EmployerWSSoap.Get_EmployerList(MC_WService.Get_EmployerListRequest request)
        {
            return base.Channel.Get_EmployerList(request);
        }
        
        public MC_WService.Employer[] Get_EmployerList()
        {
            MC_WService.Get_EmployerListRequest inValue = new MC_WService.Get_EmployerListRequest();
            inValue.Body = new MC_WService.Get_EmployerListRequestBody();
            MC_WService.Get_EmployerListResponse retVal = ((MC_WService.EmployerWSSoap)(this)).Get_EmployerList(inValue);
            return retVal.Body.Get_EmployerListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MC_WService.Get_EmployerListResponse> MC_WService.EmployerWSSoap.Get_EmployerListAsync(MC_WService.Get_EmployerListRequest request)
        {
            return base.Channel.Get_EmployerListAsync(request);
        }
        
        public System.Threading.Tasks.Task<MC_WService.Get_EmployerListResponse> Get_EmployerListAsync()
        {
            MC_WService.Get_EmployerListRequest inValue = new MC_WService.Get_EmployerListRequest();
            inValue.Body = new MC_WService.Get_EmployerListRequestBody();
            return ((MC_WService.EmployerWSSoap)(this)).Get_EmployerListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MC_WService.GetLoginDetailsResponse MC_WService.EmployerWSSoap.GetLoginDetails(MC_WService.GetLoginDetailsRequest request)
        {
            return base.Channel.GetLoginDetails(request);
        }
        
        public MC_WService.LoginDetails GetLoginDetails(string loginID)
        {
            MC_WService.GetLoginDetailsRequest inValue = new MC_WService.GetLoginDetailsRequest();
            inValue.Body = new MC_WService.GetLoginDetailsRequestBody();
            inValue.Body.loginID = loginID;
            MC_WService.GetLoginDetailsResponse retVal = ((MC_WService.EmployerWSSoap)(this)).GetLoginDetails(inValue);
            return retVal.Body.GetLoginDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MC_WService.GetLoginDetailsResponse> MC_WService.EmployerWSSoap.GetLoginDetailsAsync(MC_WService.GetLoginDetailsRequest request)
        {
            return base.Channel.GetLoginDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MC_WService.GetLoginDetailsResponse> GetLoginDetailsAsync(string loginID)
        {
            MC_WService.GetLoginDetailsRequest inValue = new MC_WService.GetLoginDetailsRequest();
            inValue.Body = new MC_WService.GetLoginDetailsRequestBody();
            inValue.Body.loginID = loginID;
            return ((MC_WService.EmployerWSSoap)(this)).GetLoginDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MC_WService.GetPayrollprovidersResponse MC_WService.EmployerWSSoap.GetPayrollproviders(MC_WService.GetPayrollprovidersRequest request)
        {
            return base.Channel.GetPayrollproviders(request);
        }
        
        public MC_WService.LoginDetails[] GetPayrollproviders(string loginID)
        {
            MC_WService.GetPayrollprovidersRequest inValue = new MC_WService.GetPayrollprovidersRequest();
            inValue.Body = new MC_WService.GetPayrollprovidersRequestBody();
            inValue.Body.loginID = loginID;
            MC_WService.GetPayrollprovidersResponse retVal = ((MC_WService.EmployerWSSoap)(this)).GetPayrollproviders(inValue);
            return retVal.Body.GetPayrollprovidersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MC_WService.GetPayrollprovidersResponse> MC_WService.EmployerWSSoap.GetPayrollprovidersAsync(MC_WService.GetPayrollprovidersRequest request)
        {
            return base.Channel.GetPayrollprovidersAsync(request);
        }
        
        public System.Threading.Tasks.Task<MC_WService.GetPayrollprovidersResponse> GetPayrollprovidersAsync(string loginID)
        {
            MC_WService.GetPayrollprovidersRequest inValue = new MC_WService.GetPayrollprovidersRequest();
            inValue.Body = new MC_WService.GetPayrollprovidersRequestBody();
            inValue.Body.loginID = loginID;
            return ((MC_WService.EmployerWSSoap)(this)).GetPayrollprovidersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MC_WService.Get_EmployerGroupWorkTraysResponse MC_WService.EmployerWSSoap.Get_EmployerGroupWorkTrays(MC_WService.Get_EmployerGroupWorkTraysRequest request)
        {
            return base.Channel.Get_EmployerGroupWorkTrays(request);
        }
        
        public MC_WService.EmployerGroupWorkTrays[] Get_EmployerGroupWorkTrays(string loginID)
        {
            MC_WService.Get_EmployerGroupWorkTraysRequest inValue = new MC_WService.Get_EmployerGroupWorkTraysRequest();
            inValue.Body = new MC_WService.Get_EmployerGroupWorkTraysRequestBody();
            inValue.Body.loginID = loginID;
            MC_WService.Get_EmployerGroupWorkTraysResponse retVal = ((MC_WService.EmployerWSSoap)(this)).Get_EmployerGroupWorkTrays(inValue);
            return retVal.Body.Get_EmployerGroupWorkTraysResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MC_WService.Get_EmployerGroupWorkTraysResponse> MC_WService.EmployerWSSoap.Get_EmployerGroupWorkTraysAsync(MC_WService.Get_EmployerGroupWorkTraysRequest request)
        {
            return base.Channel.Get_EmployerGroupWorkTraysAsync(request);
        }
        
        public System.Threading.Tasks.Task<MC_WService.Get_EmployerGroupWorkTraysResponse> Get_EmployerGroupWorkTraysAsync(string loginID)
        {
            MC_WService.Get_EmployerGroupWorkTraysRequest inValue = new MC_WService.Get_EmployerGroupWorkTraysRequest();
            inValue.Body = new MC_WService.Get_EmployerGroupWorkTraysRequestBody();
            inValue.Body.loginID = loginID;
            return ((MC_WService.EmployerWSSoap)(this)).Get_EmployerGroupWorkTraysAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MC_WService.GetEmployerProcessGroupTrayDetailsResponse MC_WService.EmployerWSSoap.GetEmployerProcessGroupTrayDetails(MC_WService.GetEmployerProcessGroupTrayDetailsRequest request)
        {
            return base.Channel.GetEmployerProcessGroupTrayDetails(request);
        }
        
        public MC_WService.EmployerGroupWorkTrayDetails[] GetEmployerProcessGroupTrayDetails(string processTypdID, int paylocationID, string trayID)
        {
            MC_WService.GetEmployerProcessGroupTrayDetailsRequest inValue = new MC_WService.GetEmployerProcessGroupTrayDetailsRequest();
            inValue.Body = new MC_WService.GetEmployerProcessGroupTrayDetailsRequestBody();
            inValue.Body.processTypdID = processTypdID;
            inValue.Body.paylocationID = paylocationID;
            inValue.Body.trayID = trayID;
            MC_WService.GetEmployerProcessGroupTrayDetailsResponse retVal = ((MC_WService.EmployerWSSoap)(this)).GetEmployerProcessGroupTrayDetails(inValue);
            return retVal.Body.GetEmployerProcessGroupTrayDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MC_WService.GetEmployerProcessGroupTrayDetailsResponse> MC_WService.EmployerWSSoap.GetEmployerProcessGroupTrayDetailsAsync(MC_WService.GetEmployerProcessGroupTrayDetailsRequest request)
        {
            return base.Channel.GetEmployerProcessGroupTrayDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MC_WService.GetEmployerProcessGroupTrayDetailsResponse> GetEmployerProcessGroupTrayDetailsAsync(string processTypdID, int paylocationID, string trayID)
        {
            MC_WService.GetEmployerProcessGroupTrayDetailsRequest inValue = new MC_WService.GetEmployerProcessGroupTrayDetailsRequest();
            inValue.Body = new MC_WService.GetEmployerProcessGroupTrayDetailsRequestBody();
            inValue.Body.processTypdID = processTypdID;
            inValue.Body.paylocationID = paylocationID;
            inValue.Body.trayID = trayID;
            return ((MC_WService.EmployerWSSoap)(this)).GetEmployerProcessGroupTrayDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MC_WService.Get_EmployerGroupWorkTrayUsersResponse MC_WService.EmployerWSSoap.Get_EmployerGroupWorkTrayUsers(MC_WService.Get_EmployerGroupWorkTrayUsersRequest request)
        {
            return base.Channel.Get_EmployerGroupWorkTrayUsers(request);
        }
        
        public MC_WService.EmployerGroupWorkTrayUser[] Get_EmployerGroupWorkTrayUsers(string loginID)
        {
            MC_WService.Get_EmployerGroupWorkTrayUsersRequest inValue = new MC_WService.Get_EmployerGroupWorkTrayUsersRequest();
            inValue.Body = new MC_WService.Get_EmployerGroupWorkTrayUsersRequestBody();
            inValue.Body.loginID = loginID;
            MC_WService.Get_EmployerGroupWorkTrayUsersResponse retVal = ((MC_WService.EmployerWSSoap)(this)).Get_EmployerGroupWorkTrayUsers(inValue);
            return retVal.Body.Get_EmployerGroupWorkTrayUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MC_WService.Get_EmployerGroupWorkTrayUsersResponse> MC_WService.EmployerWSSoap.Get_EmployerGroupWorkTrayUsersAsync(MC_WService.Get_EmployerGroupWorkTrayUsersRequest request)
        {
            return base.Channel.Get_EmployerGroupWorkTrayUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<MC_WService.Get_EmployerGroupWorkTrayUsersResponse> Get_EmployerGroupWorkTrayUsersAsync(string loginID)
        {
            MC_WService.Get_EmployerGroupWorkTrayUsersRequest inValue = new MC_WService.Get_EmployerGroupWorkTrayUsersRequest();
            inValue.Body = new MC_WService.Get_EmployerGroupWorkTrayUsersRequestBody();
            inValue.Body.loginID = loginID;
            return ((MC_WService.EmployerWSSoap)(this)).Get_EmployerGroupWorkTrayUsersAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EmployerWSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.EmployerWSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EmployerWSSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://172.22.80.129/employerWS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.EmployerWSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://172.22.80.129/employerWS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            EmployerWSSoap,
            
            EmployerWSSoap12,
        }
    }
}
